name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-dev

    - name: Deploy via SFTP
      uses: appleboy/scp-action@v0.1.0
      with:
        host: ${{ secrets.SFTP_SERVER }}
        username: ${{ secrets.SFTP_USERNAME }}
        password: ${{ secrets.SFTP_PASSWORD }}
        source: "./"
        target: "/home2/fredta05/filmes"
        port: 2222
        rm: true