name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Verificar sintaxe php
      run: |
        find src -name "*.php" -exec php -l {} \;

    - name: PHP Code Beautifier and Fixer
      run: vendor/bin/phpcbf --standard=PSR12 src

    - name: PHP Code Sniffer
      uses: php-actions/phpcs@v1
      with:
        php_version: 8.1
        path: src/Controller/Home/
        standard: phpcs.xml