name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Verificar sintaxe php
      run: |
        find src -name "*.php" -exec php -l {} \;

    # Corrigi a sintaxe
    - name: PHP Code Beautifier and Fixer
      run: vendor/bin/phpcbf --standard=PSR12 src

    # Verifica a sintaxe
    - name: PHP Code Sniffer
      uses: php-actions/phpcs@v1
      with:
        php_version: 8.1
        path: src/Controller/Home/
        standard: phpcs.xml