name: Security

on: [push, pull_request]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run security analysis
      uses: github/codeql-action/analyze@v1
      with:
        category: 'security'